Let's get started! First, we will add additional hooks to the mkinitcpio config.
These are required for unlocking the root partition at boot time. If you are
using a non-US console keymap or a non-default console font (you aren't if you
have only been following this script so far), we also need to add the
sd-vconsole hook.

Additionally, we will be adding the btrfs binary to the initial ramdisk so we
have access to it in emergency mode.