Let's get started! By default, mkinitcpio is responsible for creating the
initramfs on Arch Linux. initramfs are build per kernel, with kernel-specific
configuration residing in preset files in /etc/mkinitcpio.d. General
configuration should be done in /etc/mkinitcpio.conf. mkinitcpio is also able
to create (or offload the creation of) UKIs that include the generated
initramfs.

First, we will add btrfs to the BINARIES array. Binaries added there will be
available in the initramfs and thus in an emergency shell if boot fails while
in the initramfs stage. Adding the btrfs binary allows us to make file system
checks from the emergency shell.

Then, we will add additional hooks to the HOOKS array in mkinitcpio.conf. Hooks
are scripts that describe and adapt the initramfs environment. We will add all
hooks required for unlocking the root partition at boot. If you are using a
non-US console keymap or want to use a console font other than the default, we
also need to add the sd-vconsole hook.
