We have created a uki.conf file at /etc/kernel/uki.conf. This file contains
settings for creating UKIs, among them those relevant to Secure Boot. Unless you
really know what you are doing, you should not change any of these settings.
Nevertheless, here is an overview of the current settings in the configuration
file:
    - SignKernel: whether or not the UKI should be signed with the Secure Boot
        key; set to true obviously
    - SecureBootSigningTool: the name of the binary used for signing the UKI on
        rebuilds; set to systemd-sbsign as it is included with systemd
    - SecureBootPrivateKey: path to the private key used for signing; set to our
        own generated key
    - SecureBootCertificate: path to the certificate or public key used for
        verifying the UKI; set to our own generated key
