A configuration file for one zram device has been written to
zram-generator.conf. Have a look at the config file. In most cases, no further
customization should be necessary; zram-size is set to its default value and
zstd will be used for compression.