Configuration for zram block devices is handled in a file called zram-
generator.conf, which we will open for editing. Each header in this file,
enclosed in brackets, represents one zram device.

We have set up one zram block device, which should be sufficient for almost all
use cases. No further editing should be necessary. Nevertheless, here's an
overview of the options (currently just one) set in zram-generator.conf at this
point:
    - zram-size: how much space the zram device may take up at most; set to
        half of the available RAM, but at least 4096MB
